### ISSUE TITLE
M2 + WSL + Jupyter Notebook = kernel timeout

### ISSUE THREAD

**Issue by galettof** [radoslavraynov/Macaulay2-Jupyter-Kernel#4]
Hello!

I installed Ubuntu 18.04 on Windows 10 using the Windows Subsystem for Linux, then I installed M2 1.15 in Ubuntu. Next I installed Jupyter Notebook and the M2 Jupyter kernel (via pip3). I can run M2 within a Jupyter notebook from a browser (Chrome and Edge). I ran the following:

```
A=QQ[x_(1,1)..x_(4,6)]
G=genericMatrix(A,6,4)
I=minors(3,G);
betti res I
```

The first three lines ran okay, but the last one produced the following message:

`[KERNEL ENFORCED TIMEOUT]`

after about 5 seconds. If I run the same commands in a terminal, the last line returns a Betti table after about 8 seconds.

Any idea how I might try to fix this?

Thank you,
Fred.

**Comment by rz10x** [comment]
Hi Federico, that is intended behavior and documented in entries 14 and 24 on the [demo](https://nbviewer.jupyter.org/github/radoslavraynov/Macaulay2-Jupyter-Kernel/blob/master/demo/demo.ipynb) page. Take a look and let me know if it fixes your issue.

I am open to any and all suggestions! (I can now rewrite the code using Macaulay2/M2#929 but I don't want do it unless there's interest.)

**Comment by galettof** [comment]
Hi Radoslav,

Thank you very much for the quick reply. I should have looked at the documentation first, sorry about that!

The timeout magic command fixed the problem for me.

Cheers,
Fred.
