### ISSUE TITLE
texmacs mode output

### ISSUE THREAD

**Issue by FatemehTarashi** [radoslavraynov/Macaulay2-Jupyter-Kernel#5]
The output didn't save as tex or pdf when we changed mode as texmacs with --%mode=texmacs.

**Comment by rz10x** [comment]
that's probably because `texmacs` mode is output and displayed as HTML; the other modes' output is plain text. the renderer isn't really a part of the kernel, so I'll have to check if there's an easy workaround. I can look into over the next couple of weeks.
